name: Track deployment frequency

on:
  push:
    branches:
      - develop

#   schedule:
#     - cron: "*/2 * * * *" #test
#     - cron: "0 0 * * 1" 
#     - cron: "0 0 * * 5"

permissions:
  id-token: write
  contents: read

jobs:
  deployment-frequency:
    name: Deployment frequency scan
    runs-on: ubuntu-20.04

    steps:
    - name: Retrieve deployment frequency
      uses: DeveloperMetrics/deployment-frequency@main
      with:
        workflows: 'AWS Trivy Scan'
        actions-token: "${{ secrets.GITHUB_TOKEN }}"
        default-branch: "develop"
    

    - name: Retrieve lead time to changes
      uses: DeveloperMetrics/lead-time-for-changes@main
      with:
        workflows: 'AWS Trivy Scan'
        actions-token: "${{ secrets.GITHUB_TOKEN }}"
        default-branch: "develop"
