name: spiderman

on:
  pull_request:
    branches:
      - main

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: pip install --upgrade pip
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run MyPy on Python files in src directory
      run: mypy --ignore-missing-imports --disallow-untyped-defs --warn-return-any src

