



name: AWS Trivy Scan

on:
  push:
    branches:
      - develop

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read 

jobs:
  scan:
    name: AWS Scan
    runs-on: ubuntu-20.04

    steps:
      - name: Send Slack Message - Generating Report
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Generating Trivy Report :robot_face:\"}" ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.52.1
          sudo apt-get update && sudo apt-get install -y jq

      - name: Send Slack Message - Running Trivy Scanner
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Running Trivy Scanner :hourglass_flowing_sand:\"}" ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::590183661216:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Run Trivy vulnerability scanner
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          TRIVY_OUTPUT=trivy_report_${TIMESTAMP}.json
          trivy aws --region us-east-1 --format json --output ${TRIVY_OUTPUT} --severity MEDIUM
          ls -l ${TRIVY_OUTPUT}

      - name: Send Slack Message - Uploading Report to S3
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Uploading Trivy Report to S3 :cloud:\"}" ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Upload Trivy report to S3
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          TRIVY_OUTPUT=trivy_report_${TIMESTAMP}.json
          aws s3 cp ${TRIVY_OUTPUT} s3://github-actions-s3-v1/trivy_reports/${TRIVY_OUTPUT}

      - name: Send Slack Message - Report Uploaded
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Trivy Report uploaded to S3 :white_check_mark:\"}" ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Slack Message - Uploading Report to Slack
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          TRIVY_OUTPUT=trivy_report_${TIMESTAMP}.json
          SLACK_CHANNEL="#experiments"
          SLACK_TITLE="Trivy Report ${TIMESTAMP}"
          SLACK_INITIAL_MESSAGE="Uploading Trivy Report to Slack :file_upload:"
          SLACK_UPLOAD_MESSAGE="Trivy Report uploaded to Slack :white_check_mark:"

        
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${SLACK_INITIAL_MESSAGE}\", \"channel\":\"${SLACK_CHANNEL}\"}" ${{ secrets.SLACK_WEBHOOK_URL }}

          
          UPLOAD_RESPONSE=$(curl -F file=@${TRIVY_OUTPUT} -F "initial_comment=${SLACK_TITLE}" -F channels=${SLACK_CHANNEL} -H "Authorization: Bearer ${SLACK_TOKEN}" https://slack.com/api/files.upload)

          
          if [[ $(echo ${UPLOAD_RESPONSE} | jq -r '.ok') == "true" ]]; then
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${SLACK_UPLOAD_MESSAGE}\", \"channel\":\"${SLACK_CHANNEL}\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
          else
            echo "Failed to upload Trivy report to Slack: $(echo ${UPLOAD_RESPONSE} | jq -r '.error')"
            exit 1
          fi

      - name: Cleanup
        if: always()
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          TRIVY_OUTPUT=trivy_report_${TIMESTAMP}.json
          rm -f ${TRIVY_OUTPUT}

