name: AWS Trivy Scan

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read 

jobs:
  scan:
    name: AWS Scan
    runs-on: ubuntu-20.04

    steps:
      - name: Send Slack Message - Generating Report
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Generating Trivy Report :robot_face:\"}" ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.52.1
          sudo apt-get update && sudo apt-get install -y jq



      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::590183661216:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Run Trivy vulnerability scanner
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          TRIVY_OUTPUT=trivy_report_${TIMESTAMP}.json
          trivy aws --region us-east-1 --format json --output ${TRIVY_OUTPUT} --severity MEDIUM
          ls -l ${TRIVY_OUTPUT}



      - name: Upload Trivy report to S3
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          TRIVY_OUTPUT=trivy_report_${TIMESTAMP}.json
          aws s3 cp ${TRIVY_OUTPUT} s3://github-actions-s3-v1/trivy_reports/${TRIVY_OUTPUT}

      - name: Send Slack Message - Report Uploaded
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Trivy Report uploaded to S3 :white_check_mark:\"}" ${{ secrets.SLACK_WEBHOOK_URL }}

     
      - name: Set up environment variables
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: general
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: "Trivy Report"
          SLACK_USERNAME: trivy_success
        run: |
          export TIMESTAMP=$(date +%Y%m%d)
          echo "TIMESTAMP=${TIMESTAMP}" >> $GITHUB_ENV

      - name: Slack Notification for File Upload
        uses: rtCamp/action-slack-notify@v2
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_channel: ${{ env.SLACK_CHANNEL }}
          slack_color: ${{ env.SLACK_COLOR }}
          slack_icon: ${{ env.SLACK_ICON }}
          slack_message: ${{ env.SLACK_TITLE }} Upload for ${TIMESTAMP}
          slack_username: ${{ env.SLACK_USERNAME }}
          slack_file_upload: "trivy_report_${TIMESTAMP}.json"

      - name: Cleanup
        if: always()
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          TRIVY_OUTPUT=trivy_report_${TIMESTAMP}.json
          rm -f ${TRIVY_OUTPUT}

