name: Trivy Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_Linux-64bit.tar.gz
          tar zxvf trivy_Linux-64bit.tar.gz
          sudo mv trivy /usr/local/bin/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
            role-to-assume: arn:aws:iam::590183661216:role/GitHubAction-AssumeRoleWithAction
            role-session-name: GitHub_to_AWS_via_FederatedOIDC
            aws-region: us-east-1

      - name: Run Trivy scan
        run: trivy aws --region us-east-1

