

name: AWS Trivy Scan

on:
  push:
    branches:
      - develop

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read 

jobs:
  scan:
    name: AWS Scan
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.52.1
          sudo apt-get update && sudo apt-get install -y jq

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::590183661216:role/GitHubAction-AssumeRoleWithAction
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1

      - name: Run Trivy vulnerability scanner
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          TRIVY_OUTPUT=trivy_report_${TIMESTAMP}.json
          trivy aws --region us-east-1 --format json --output ${TRIVY_OUTPUT} --severity MEDIUM
          

      - name: Upload Trivy report to S3
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          TRIVY_OUTPUT=trivy_report_${TIMESTAMP}.json
          aws s3 cp ${TRIVY_OUTPUT} s3://github-actions-s3-v1/trivy_reports/${TRIVY_OUTPUT}

      - name: Send results to Slack
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          TRIVY_OUTPUT=trivy_report_${TIMESTAMP}.json
          SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}
          curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"Results uploaded to S3 for ${TRIVY_OUTPUT}\"}" ${SLACK_WEBHOOK_URL}

      - name: Cleanup
        if: always()
        run: |
          TIMESTAMP=$(date +%Y%m%d)
          TRIVY_OUTPUT=trivy_report_${TIMESTAMP}.json
          rm -f ${TRIVY_OUTPUT}

